### ISSUE TITLE
autoplayergui: exit with error

### ISSUE THREAD

**Issue by pat1** [pat1/autoradio#22]
with message:
error getting player playlist

**Comment by pat1** [comment]
added tracebeck fo debug

**Comment by pat1** [comment]
update gtktree
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 251, in make_list
    for track in  self.tl.GetTracksMetadata( self.tl.Tracks):
  File "/usr/lib/python2.7/site-packages/autoradio/pydbusdecorator/dbus_method.py", line 91, in dbusWrapedMethod
    return self._call_dbus(obj, *args, **kw)
  File "/usr/lib/python2.7/site-packages/autoradio/pydbusdecorator/dbus_method.py", line 66, in _call_dbus
    dbus_result = bus_meth(*args, **kw)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Python.KeyError: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/site-packages/autoradio/autoplayer/player.py", line 510, in GetTracksMetadata
    myattr= getattr(self.player.playlist[id],attr,None)
KeyError: dbus.String(u'32009')


Error getting player playlist

**Comment by pat1** [comment]
now do not exit but print a trace:
```
PlaybackStatus Playing
PlaybackStatus Playing
PlaybackStatus Playing
PlaybackStatus Playing
PlaybackStatus Playing
PlaybackStatus Playing
PlaybackStatus Stopped
PlaybackStatus Playing
PlaybackStatus Stopped
PlaybackStatus Playing
update gtktree
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
Traceback (most recent call last):
  File "/usr/bin/autoplayergui", line 272, in Len
    cell.set_property('text', convert_ns(track[0].get(u'mpris:length',"")))
  File "/usr/bin/autoplayergui", line 24, in convert_ns
    s,ns = divmod(t, 1000000)
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
update gtktree
update gtktree
update gtktree

```

**Comment by pat1** [comment]
cannot replicate
