### ISSUE TITLE
autoradiod errors

### ISSUE THREAD

**Issue by pat1** [pat1/autoradio#35]
```
Daemon stderr output
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/autoradio/managempris.py", line 144, in ManagePlayer
    aud.playlist_add_atpos("file://"+media,pos)
TypeError: can only concatenate str (not "bytes") to str
Daemon stderr output
Daemon stderr output
```
```
Daemon stderr output
That's 6 out file(s).
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/autoradio/managempris.py", line 144, in ManagePlayer
    aud.playlist_add_atpos("file://"+media.decode("utf-8"),pos)
AttributeError: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/autoradio/managempris.py", line 144, in ManagePlayer
    aud.playlist_add_atpos("file://"+media.decode("utf-8"),pos)
AttributeError: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/autoradio/managempris.py", line 144, in ManagePlayer
    aud.playlist_add_atpos("file://"+media.decode("utf-8"),pos)
AttributeError: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/autoradio/managempris.py", line 144, in ManagePlayer
    aud.playlist_add_atpos("file://"+media.decode("utf-8"),pos)
AttributeError: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/autoradio/managempris.py", line 144, in ManagePlayer
    aud.playlist_add_atpos("file://"+media.decode("utf-8"),pos)
AttributeError: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/autoradio/managempris.py", line 144, in ManagePlayer
    aud.playlist_add_atpos("file://"+media.decode("utf-8"),pos)
AttributeError: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/autoradio/managempris.py", line 144, in ManagePlayer
    aud.playlist_add_atpos("file://"+media.decode("utf-8"),pos)
AttributeError: 'str' object has no attribute 'decode'
That's 92 out file(s).
```
```
2024-01-18 12:12:27 - root - INFO - Managempris: write   in django: la storia continua
2024-01-18 12:12:27 - root - INFO - Managempris: written in django: la storia continua
2024-01-18 12:16:01 - root - ERROR - Traceback (most recent call last):
  File "/usr/bin/autoradiod", line 149, in main
  File "/usr/lib/python3.9/site-packages/autoradio/autoradio_core.py", line 435, in get_all_refine
  File "/usr/lib/python3.9/site-packages/autoradio/autoradio_core.py", line 369, in get_all
  File "/usr/lib/python3.9/site-packages/autoradio/gest_spot.py", line 89, in get_fasce
  File "/usr/lib/python3.9/site-packages/autoradio/gest_spot.py", line 175, in get_fascia_playlist_media
  File "/usr/lib64/python3.9/tempfile.py", line 336, in mkstemp
  File "/usr/lib64/python3.9/tempfile.py", line 255, in _mkstemp_inner
OSError: [Errno 24] Troppi file aperti: '/tmp/tmpe_nq3ps1'

```

**Comment by pat1** [comment]
rimane solo:
```
2024-01-18 12:16:01 - root - ERROR - Traceback (most recent call last):
  File "/usr/bin/autoradiod", line 149, in main
  File "/usr/lib/python3.9/site-packages/autoradio/autoradio_core.py", line 435, in get_all_refine
  File "/usr/lib/python3.9/site-packages/autoradio/autoradio_core.py", line 369, in get_all
  File "/usr/lib/python3.9/site-packages/autoradio/gest_spot.py", line 89, in get_fasce
  File "/usr/lib/python3.9/site-packages/autoradio/gest_spot.py", line 175, in get_fascia_playlist_media
  File "/usr/lib64/python3.9/tempfile.py", line 336, in mkstemp
  File "/usr/lib64/python3.9/tempfile.py", line 255, in _mkstemp_inner
OSError: [Errno 24] Troppi file aperti: '/tmp/tmpe_nq3ps1'
```
